### ISSUE TITLE
Julia 0.6 WARNING: Compat.UTF8String is deprecated, use String instead

### ISSUE THREAD

**Issue by ko56** [JuliaIO/Formatting.jl#42]
Apparently some update is needed for Julia 0.6:

./src/formatexpr.jl:81:    prefix::Compat.UTF8String
./src/formatexpr.jl:82:    suffix::Compat.UTF8String
./src/formatexpr.jl:84:    inter::Vector{Compat.UTF8String}
./src/formatexpr.jl:103:    return (p, convert(Compat.UTF8String, pre))
./src/formatexpr.jl:118:    prefix = convert(Compat.UTF8String, "")
./src/formatexpr.jl:119:    suffix = convert(Compat.UTF8String, "")
./src/formatexpr.jl:121:    inter = Compat.UTF8String[]

**Comment by jmkuhn** [comment]
The master branch is updated for 0.6:
```
Pkg.checkout("Formatting")
```
It would be nice to have a released version with these changes.

**Comment by nalimilan** [comment]
Done.
