### ISSUE TITLE
Wrong output of "fmt()" function for exponent formatting of some numbers

### ISSUE THREAD

**Issue by iamfedoroff** [JuliaIO/Formatting.jl#61]
Function "fmt()" returns wrong result if I want to represent a number from the range (1e-21, 1e-31) in exponent format:

```
julia> using Formatting

julia> fmt("1.0e", 1e-20)   # OK
"1.e-20"

julia> fmt("1.1e", 1e-20)   # OK
"1.0e-20"

julia> fmt("1.0e", 1e-21)   # Wrong
"0.e-21"

julia> fmt("1.1e", 1e-21)   # Wrong
"0.10e-21"

julia> fmt("1.0e", 1e-31)   # OK
"1.e-31"

julia> fmt("1.1e", 1e-31)   # Wrong
"0.10e-31"

julia> fmt("1.0e", 1e-32)   # OK
"1.e-32"

julia> fmt("1.1e", 1e-32)   # OK
"1.0e-32"
```
For numbers larger than 1e-20 and smaller than 1e-31 it seems that everything is fine. However, in the range between, the output of "fmt()" function is wrong. For example, instead of 1e-21 it shows "0.1e-21".

**Comment by jmkuhn** [comment]
Fixed with PR #63 and Release v0.3.2
