### ISSUE TITLE
Tag a new version due to Julia 1.6

### ISSUE THREAD

**Issue by ronisbr** [JuliaIO/Formatting.jl#94]
Hi!

It seems we are approaching the release of Julia 1.6. The current version o Formatting.jl does not work in 1.6 due to https://github.com/JuliaIO/Formatting.jl/commit/d2e031acabbf8ce95bedf02fe34c73e8f8015ff0

Is it possible to tag a new version to fix this?

**Comment by bkamins** [comment]
@nalimilan - you are member of JuliaIO, so could you please have a look at it? Thank you!

**Comment by nalimilan** [comment]
I've filed https://github.com/JuliaIO/Formatting.jl/pull/95 as without it registration will need somebody to manually merge the PR in General.jl. I'll merge it and tag a release if nobody objects.

**Comment by nalimilan** [comment]
Done: https://github.com/JuliaRegistries/General/pull/25747

**Comment by ronisbr** [comment]
Thanks @nalimilan  !
